
version: '3.4'

networks:
  frontend:
  backend:

services:

   mssqlserver:
     image: "mcr.microsoft.com/mssql/server:latest"
     environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: EventCatalogApi(!)
     ports:
       - "1448:1433"
     container_name: eventssqlserver
     networks:
       - backend

   tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventCatalogApi(!)
    ports:
      - "1449:1433"
    container_name: eventstokensqlserver
    networks:
      - backend

   eventcatalogapi:
     image: eventbrite/eventcatalogapi
     build:
       context: .\EventCatalogApi
       dockerfile: Dockerfile
     environment:
       Externalbaseurl: http://localhost:7100
       DatabaseServer: mssqlserver
       DatabaseName: EventManageDbTwo
       DatabaseUser: sa
       DatabasePassword: EventCatalogApi(!)
     ports:
       - "7100:80"
     container_name: eventcatalogapi
     networks:
       - frontend
       - backend
     depends_on:
       - mssqlserver
       
   webmvc: 
     image: events/webmvc
     build:
       context: .\WebMvc
       dockerfile: Dockerfile
     environment:
       ASPETCORE_ENVIRONMENT: Development
       EventCatalogUrl: http://eventcatalogapi
       IdentityUrl: http://172.20.176.1:7800
       CallbackUrl: http://localhost:8000

     ports:
       - "8000:80"
     container_name: eventbrite
     networks:
       - frontend
     depends_on:
       - eventcatalogapi
       - tokenserver
   tokenserver:
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:8000
      BasketApiClient: http://localhost:7510
      OrderApiClient: http://localhost:7520
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokensqlserver

