
version: '3.4'

networks:
  frontend:
  backend:

services:

   mssqlserver:
     image: "mcr.microsoft.com/mssql/server:latest"
     environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: EventCatalogApi(!)
     ports:
       - "1448:1433"
     container_name: eventssqlserver
     networks:
       - backend

   tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventCatalogApi(!)
    ports:
      - "1449:1433"
    container_name: eventstokensqlserver
    networks:
      - backend

   eventcatalogapi:
     image: eventbrite/eventcatalogapi
     build:
       context: .\EventCatalogApi
       dockerfile: Dockerfile
     environment:
       Externalbaseurl: http://localhost:7100
       DatabaseServer: mssqlserver
       DatabaseName: EventManageDbTwo
       DatabaseUser: sa
       DatabasePassword: EventCatalogApi(!)
     ports:
       - "7100:80"
     container_name: eventcatalogapi
     networks:
       - frontend
       - backend
     depends_on:
       - mssqlserver

   ticketorderapi:
     image: eventbrite/ticketorderapi
     build:
       context: .\TicketOrderApi
       dockerfile: Dockerfile
     environment:
       ASPNETCORE_ENVIRONMENT: Development
       #IdentityUrl: http://192.168.1.102:7800
       DatabaseServer: mssqlserver
       DatabaseName: EventManageDbTwo
       DatabaseUser: sa
       DatabasePassword: EventCatalogApi(!)
     logging: 
       driver: "json-file"
       options: {
          max-size: "200k",
          max-file: "10"
      }
     ports:
       - "7200:80"
     container_name: ticketorderapi
     networks:
       - frontend
       - backend
     depends_on:
       #- tokenserver
       - mssqlserver
       - rabbitmq

   rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq
     hostname: myrabbitmq
     ports:
       - "15672:15672"
       - "5672:5672"
       - "5671:5671"
     volumes:
       - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
     networks:
       - backend 

   webmvc: 
     image: events/webmvc
     build:
       context: .\WebMvc
       dockerfile: Dockerfile
     logging: 
       driver: "json-file"
       options: {
          max-size: "200k",
          max-file: "10"
      }
     environment:
       TicketOrderUrl: http://ticketorderapi
       EventCatalogUrl: http://eventcatalogapi
       IdentityUrl: http://172.20.176.1:7800
       CallbackUrl: http://localhost:8000
       StripePublicKey: pk_test_PZScD6MMQk4mR7MEx65yXuxQ00n6AeQWBi
       StripePrivateKey: sk_test_J8H9AKCSKT3IyaRTFgLpL6X200LU34kY3l
     ports:
       - "8000:80"
     container_name: eventbrite
     networks:
       - frontend
     depends_on:
       - eventcatalogapi
       - tokenserver
   tokenserver:
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:8000
      BasketApiClient: http://localhost:7510
      OrderApiClient: http://localhost:7520
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokensqlserver

